### ISSUE TITLE
yarn addがDockerfileにてインストールされない

### ISSUE THREAD

**Issue by lxzLocus** [lxzLocus/ASEticle_Front#1]
Next.js内にてRadix UIフレームワークを利用しようと，インストールするため`Dockerfile`内に`RUN yarn add @radix-ui/themes`を追記．ブランチを現在の`UI`にした状態でVSCode内ターミナルより`$ docker compose up --build -d`を実行するも，`$ yarn list`で確認してみてもインストールされていない．
ビルド中のターミナルを見てみるとエラーは起きずに`RUN`コマンドは実行できている模様．`npm install`でのインストールも試みたが，同じくインストールされなかった．

`Dockerfile`
```
FROM node:20.0-alpine

WORKDIR /app


# Install npm package
RUN npm install -g next@14.2.4 
RUN yarn add @radix-ui/themes
```

`docker-compose`
```
services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "49513:3000"
    #restart: always
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /app
```

**Comment by lxzLocus** [comment]
# 解決

Dockerfileの変更かは不明
Dockerfileとdocker-compose変更して解決．

## `npm list` とすると`extraneous` 無関係と出る．
依存関係外れたか？？

---

`Dockerfile`
`COPY package*.json ./`と最後の`COPY . .`

```
FROM node:alpine3.19

WORKDIR /app

COPY package*.json ./
COPY yarn.lock .

# Install npm package
RUN npm install npm
RUN npm install -g next@14.2.4 
RUN yarn add @radix-ui/themes

COPY . .
```

---

`docker-compose.yml`

##`- /app/node_modules`←これ重要

`volumes`内に`- /app/node_modules`の記述を加えるとインストールが反映されるようになった．

```
services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "49513:3000"
    #restart: always
    tty: true
    volumes:
      - /app/node_modules # ←追加
      - type: bind
        source: ./
        target: /app
```
